{% set name = "pkg-config" %}
{% set version = "1.4.4" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 23d64f7a82dec11baf00d09c5a9199b5dff28830723286e721f30b3b4c721a19

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: LGPL-2.0
  license_family: GPL
  license_file: {{ name }}-{{ version }}/LGPL-2.1
  summary: pkg-config can be used in your extconf.rb to properly detect need libraries for compiling Ruby native extensions

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/ruby-gnome/{{ name }}

extra:
  recipe-maintainers:
    - sodre
