travis:
  secure:
    BINSTAR_TOKEN: MFEeEZmqGVfAivrh5DoUfjoh+2SNehMXrZFRC7V1K4WBs5SLHoMFWukp5PqI/gzUDwp2+IbRbvzYff6buZyt52v585sUzMByUHNP7GVe/zIQAdb6zydwL7tI3z8xtyFeq+QqH0n1UIdHeNSP75pv4rAMFGRNbYqtlxqpbDLSrG8C5pS/TDSOJRC4bMixKNsFcesoN8w5SzFuYyf85AcUPKOsrLn2fD+llGKs2GgYx7xUt0ciYAi49r0nxKCBtXJXZn6/l2deVP9fmPz7A/rzjdrVEh8GZVAFStmsvQXxVOUw/3FW0UuUbEFuySAOQASXObh/L5HgqmKeq08sTnRFaRQXEMvpeEvmM5tVUFqZ5rnflpP9FquZvtAnyZAfKKXpJUQOaFjchPfZ93uHOP5BQaqVpzFX9YvRuDNu9JaYrHfNYBARtl7SLhUdQ/d0POyuclc3HIJOK6OAMehJuPyCZpabFtibjaqo6ogjR3vJlKrOR4BURl1/VXz3cVvj8x8z4mS9bwlccM89kFyzJlu37g6BHz+JqYXUvLGZGdoSwVidvV3OFNlHbNMDqPo6ogzB+sEep0HpHtSTNjjvjwFh/IqkK9zVNDY/40VcLABSwcfp+B9YUD5soDGX1FaIa+NZq/IBKuiyPq7DjYkCgeqUntELhhGAFaJbUDMBzD0yLRU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
