travis:
  secure:
    BINSTAR_TOKEN: TucdeGt23b8fyM/7MELF8uuR1dOaQ4+i7KCDmjWFtYoBy4iWy9MHhv5FZEkfgEQHRJNupLP0iFLsim7ltks0s9ngGkGcLsPuuIJG0il6FDbpL+g+nOo/W7ppHFddfGr9AIIWgtCr45KYqkkob2d5pb4t0UsVJHE8S/9BETSch3oSi8e8EmDIE9J+wkgeVsxNk8D9ohiyMIm7jKBmBDvGNzVTjjuf86BgmICO+KTsfLItqgHfbZLsU3ZV8VOa4nbGlSryAMuScAzlFaLwWliYTceX5HfwQTUn87PBD3vd+54X/XV4W1YuDgiNCu/qr9szwtwCRrbbiGdl5DDIfzJ8FUQFhTJ3ec/ICYqhFFzOPKvDsAA251cTnApMjX6aC8fHshaRHF8DE2l9V+NUGT0reg/LQ/1Kg07VuMxr0UEMiZytZ6zOFybq2+6vg1rIwNTJ8YRZ2RuCAHYzzyyJK3p8ekv/5p8/XiESYmtDamlnEVuojN9G6XM/MUp4HtgvAGu5sTyc7L+8mrHPlCLEgLt7ws9RBsV+oJgGpTU53aPRtQiSlGjC+sEQkLAfVEhiq3SUmgjOcBECrFu7mg4gIzjbsEufRzSD4ja2zqEhkc9Q8dCdXEMyVu3cZVDYHgkA01b+8xGAU7clu+1ZF56y27INhogEbSQBashokXUQu9lIi7w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
